#!/bin/bash

sshpass -p pi  ssh    pi@192.168.1.100  sudo init 0
sshpass -p pi  ssh    pi@192.168.1.101  sudo init 0
sshpass -p pi  ssh    pi@192.168.1.102  sudo init 0
sshpass -p pi  ssh    pi@192.168.1.103  sudo init 0
sshpass -p pi  ssh    pi@192.168.1.104  sudo init 0
sshpass -p pi  ssh    pi@192.168.1.105  sudo init 0


